// SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: MIT
//

#pragma once

#include "source/core/nvigi.api/nvigi_version.h"

#define CORESDK_SHARED_VERSION_MAJOR NVIGI_CORESDK_VERSION_MAJOR
#define CORESDK_SHARED_VERSION_MINOR NVIGI_CORESDK_VERSION_MINOR
#define CORESDK_SHARED_VERSION_PATCH NVIGI_CORESDK_VERSION_PATCH
#define CORESDK_API_VERSION_MAJOR NVIGI_CORESDK_API_VERSION_MAJOR
#define CORESDK_API_VERSION_MINOR NVIGI_CORESDK_API_VERSION_MINOR
#define CORESDK_API_VERSION_PATCH NVIGI_CORESDK_API_VERSION_PATCH
#if defined(NVIGI_PRODUCTION)
#define BUILD_CONFIG_INFO "PRODUCTION"
#elif defined(NVIGI_DEBUG)
#define BUILD_CONFIG_INFO "DEBUG"
#elif defined(NVIGI_RELEASE)
#define BUILD_CONFIG_INFO "RELEASE"
#else
#error "Unsupported build config"
#endif

#if defined(NVIGI_PRODUCTION)
#define DISTRIBUTION_INFO "PRODUCTION"
#else
#define DISTRIBUTION_INFO "NOT FOR PRODUCTION"
#endif

